baseURL: https://mzouvelos.netlify.app
languageCode: en
title: Michalis Zouvelos
author: Michalis Zouvelos
copyright: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 6
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
pygmentsCodefencesGuessSyntax: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: vs
    codeFences: true
    guessSyntax: true
    noClasses: false
    lineNos: true
    lineNumbersInTable: true
  tableOfContents:
    endLevel: 3
    ordered: no
    startLevel: 2
params:
  theme: 
  custom_theme: "hex-colors" 
  description: "Personal website for Michalis Zouvelos, containing blogs and materials related to data science, analytics and ML."
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  favicon: 
  headingFontFamily: sans-serif
  mainSections:
  navallcaps: yes
  orgLocal:
  orgName: Michalis Zouvelos
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/mzouvelos
    - icon: linkedin
      icon_pack: fab
      url: https://www.linkedin.com/in/michalis-zouvelos-8912371b6/
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: mzouvelos/mzouvelos.rbind.io
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  header:
    - name: About
      title: About
      url: /
      weight: 1
    - name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: 2
    - name: Blog
      title: Blog
      url: /blog/
      weight: 3
    - name: Search
      title: Search
      url: /search/
      weight: 4
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
